### ISSUE TITLE
Declare FOAF namespace in bibframe.rdf

### ISSUE THREAD

**Issue by greeve** [lcnetdev/bibframe-ontology#57]
Please declare the FOAF namespace in the `rdf:RDF` tag of `bibframe.rdf`:

```
xmlns:foaf="http://xmlns.com/foaf/0.1/"
```

**Comment by thisismattmiller** [comment]
We don't define the namespace because we use the full URI in RDF for the two places it is referenced:

https://github.com/lcnetdev/bibframe-ontology/blob/master/bibframe.rdf#L326
https://github.com/lcnetdev/bibframe-ontology/blob/master/bibframe.rdf#L341

Is there a specific reason you need it defined?

**Comment by greeve** [comment]
Having the namespace facilitates easier viewing in tools that display the ontology (e.g. Protoge or [ontospy](http://lambdamusic.github.io/Ontospy/)). Also, I thought it would add consistency and follow best practices for referencing other ontologies.

**Comment by kefo** [comment]
Should be there now:  https://id.loc.gov/ontologies/bflc.rdf

**Comment by greeve** [comment]
Thanks!
