### ISSUE TITLE
New bf:Work subclasses

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/bibframe-ontology#93]
To accommodate changes in the marc2bibframe and bibframe2marc programs, the following bf:Work subclasses are proposed.

Class: MusicAudio
URI: http://id.loc.gov/ontologies/bibframe/MusicAudio
Label: Music audio
Definition: Music resource expressed in an audible form.
SubClass Of: Audio

Class: NonMusicAudio
URI: http://id.loc.gov/ontologies/bibframe/NonMusicAudio
Label: Non-music audio
Definition: Resource expressed in an audible form, including spoken word and other non-musical sounds.
SubClass Of: Audio

Class: Integrating
URI: http://id.loc.gov/ontologies/bibframe/Integrating
Label: Integrating resource
Definition: Resource that is added to or changed by updates that do not remain discrete but are integrated into the whole.
SubClass Of: Work

Class: Kit
URI: http://id.loc.gov/ontologies/bibframe/Kit
Label: Kit
Definition: Resource that contains a mixture of various components issued as a unit and intended primarily for instructional purposes.
SubClass Of: MixedMaterial

Class: Monograph
URI: http://id.loc.gov/ontologies/bibframe/Monograph
Label: Monograph
Definition: Resource that is issued as a single physical unit or intangible single logical unit.
SubClass of: Work

Class: Serial
URI: http://id.loc.gov/ontologies/bibframe/Serial
Label: Serial
Definition: Resource that is issued in successive parts, usually numbered, that has no predetermined conclusion.
SubClass Of: Work

Class: Series
URI: http://id.loc.gov/ontologies/bibframe/Series
Label: Series
Definition: Resource with a collective title that applies to a group of separate resources, each of which also has its own title.
SubClass Of: Work

**Comment by kefo** [comment]
https://id.loc.gov/ontologies/bibframe.html#c_MusicAudio
https://id.loc.gov/ontologies/bibframe.html#c_NonMusicAudio
https://id.loc.gov/ontologies/bibframe.html#c_Integrating
https://id.loc.gov/ontologies/bibframe.html#c_Kit
https://id.loc.gov/ontologies/bibframe.html#c_Monograph
https://id.loc.gov/ontologies/bibframe.html#c_Serial
https://id.loc.gov/ontologies/bibframe.html#c_Series

**Comment by schlawiner** [comment]
The addition of Monograph, Serial, Series, and Integrating as Work subclasses seem to originate from [MARC Leader 07](https://www.loc.gov/marc/bibliographic/bdleader.html) (m, s, i). 
I wonder whether **"monographic component part"** (Leader 07 a) was also considered as a new Work subclass? 

This is something we are trying to solve for modeling **journal articles** and **book chapters** in our reference database of academic literature. However, we think that things expressing that something is a part of something else (or is standalone, i.e. a monograph/item) - both classes and properies/relationships - should be at the **level of Instance** (which aligns with the fact that monograph vs serial/integrating _used to be_ expressed in Instance > bf:issuance - I do understand that the new RDA rules for moving info about diachronic resources like journals to the Work have made it necessary to change that). 

So, we are not so sure whether it would even make sense to have a hypothethical class "Monographic Component Part" be a subclass of Work. Maybe this is something that has already been discussed and that's why such as Work subclass hasn't been created?

For reference: At the moment, we have decided to express this "issuance type" info with an expanded SKOS vocabulary for mode of issuance of the Instance that includes "single unit" and "multiple unit" as topConcepts, with (Standalone) Monograph/Item, Compontent Part, Serial, Series, and Integrating (plus subtypes thereof) as narrower concepts deeper in the hiearchy.

**Comment by andand79** [comment]
@schlawiner It seems that "monographic component part", "serial component part" and "subunit" are all indeed on the instance level. Not as types, not as issuances, but as relations (i.e. dcterms:isPartOf). This can however not be said about Collection and Serial, entities that are aggregating works, and therefore, in some form, function better as work types.

The current definition of bf:Serial, derived from MARC21, still refers to issuance ("Resource that is issued in successive parts"). Moving from the MARC view of "bibliographic level" probably requires a new definition, preferably closer to LRM where a serial is more of an aggregating super work.
